### ISSUE TITLE
Add 'first timer' checkbox to proposal form

### ISSUE THREAD

**Issue by vmbrasseur** [SeaGL/osem#8]
Work started on this in #4. 

We would like to get a checkbox on the talk proposal form for tracking first-time speakers. The phrasing we chose last year is, "This will be my first time speaking at a conference." That still works well.

The UI should be a simple toggle (checkbox, etc). It should not be required for submitting a proposal.

**Comment by emanuil-tolev** [comment]
Seems completed in #4? Or does it also need to be editable after initial proposal creation, or is something else missing from this feature?

**Comment by vmbrasseur** [comment]
#4 never worked. We were in a rush and didn't have time to test it properly before deploying. We then didn't have time to troubleshoot properly afterward. All we know is: no data. ¯\_(ツ)_/¯

**Comment by differentreality** [comment]
Would it make sense to add this as your custom questions so that you don't diverge much from upstream?

Surveys are now available in upstream and you can create your own survey with your custom questions and make it available during registration (there are other options for where it shows up).

It won't give you statistics in the conference page, but it will if you go to the surveys at the question you need.

**Comment by vmbrasseur** [comment]
This is great to know, thanks @differentreality!
